import type { PhraseCard } from "@/lib/toeic/types"

/**
 * TOEIC で繰り返し出るフレーズ（コロケーション・定型表現）のカード。
 *
 * すべてこのアプリのために書き下ろしたもので、市販の単語集からの転載はない。
 * 単語を1語で覚えるのではなく、「どの語とどの語が結びつくか」で覚えるための
 * 材料としている。例文はすべてビジネス文脈にそろえた。
 */
export const PHRASE_CARDS: PhraseCard[] = [
  // ------------------------------------------------------------------
  // 動詞＋名詞（verb-noun）
  // ------------------------------------------------------------------
  {
    id: "ph-vn-01",
    category: "verb-noun",
    phrase: "meet a deadline",
    meaning: "締め切りに間に合わせる",
    example: "The team worked late to meet the deadline for the tender.",
    exampleTranslation: "チームは入札の締め切りに間に合わせるため遅くまで働いた。",
    note: "meet は「（要求・基準）を満たす」。meet the requirements、meet expectations も同じ用法。",
  },
  {
    id: "ph-vn-02",
    category: "verb-noun",
    phrase: "place an order",
    meaning: "注文する",
    example: "Please place your order by Friday to receive the discount.",
    exampleTranslation: "割引を受けるには金曜日までにご注文ください。",
    note: "「注文を受ける」は take an order、「注文を処理する」は process an order。",
  },
  {
    id: "ph-vn-03",
    category: "verb-noun",
    phrase: "reach an agreement",
    meaning: "合意に達する",
    example: "The two firms reached an agreement after three rounds of talks.",
    exampleTranslation: "両社は3回の協議を経て合意に達した。",
  },
  {
    id: "ph-vn-04",
    category: "verb-noun",
    phrase: "take effect",
    meaning: "（規則などが）発効する、効力を持つ",
    example: "The revised policy takes effect on 1 April.",
    exampleTranslation: "改訂された規程は4月1日に発効する。",
    note: "come into effect もほぼ同じ意味。「実施する」側からは put ... into effect。",
  },
  {
    id: "ph-vn-05",
    category: "verb-noun",
    phrase: "conduct a survey",
    meaning: "調査を行う",
    example: "We conducted a survey of 500 customers last month.",
    exampleTranslation: "先月、顧客500人を対象に調査を行った。",
    note: "conduct は「（調査・研修・面接などを）実施する」。conduct an interview も頻出。",
  },
  {
    id: "ph-vn-06",
    category: "verb-noun",
    phrase: "issue a refund",
    meaning: "返金する",
    example: "We will issue a refund within five business days.",
    exampleTranslation: "5営業日以内に返金いたします。",
    note: "issue は「（公式に）発行する・出す」。issue a permit、issue a statement も同様。",
  },
  {
    id: "ph-vn-07",
    category: "verb-noun",
    phrase: "address a concern",
    meaning: "懸念に対応する",
    example: "The manager addressed the staff's concerns about the new shifts.",
    exampleTranslation: "部長は新しいシフトに対する職員の懸念に対応した。",
    note: "address は「住所」だけでなく「（問題に）取り組む」という動詞でも頻出。",
  },
  {
    id: "ph-vn-08",
    category: "verb-noun",
    phrase: "implement a policy",
    meaning: "方針を実施する",
    example: "The company implemented a remote work policy last year.",
    exampleTranslation: "その会社は昨年、在宅勤務の方針を導入した。",
  },
  {
    id: "ph-vn-09",
    category: "verb-noun",
    phrase: "waive a fee",
    meaning: "手数料を免除する",
    example: "The bank agreed to waive the transfer fee for the first year.",
    exampleTranslation: "銀行は初年度の振込手数料を免除することに同意した。",
    note: "waive は「（権利・料金を）放棄する、免除する」。広告文で頻出。",
  },
  {
    id: "ph-vn-10",
    category: "verb-noun",
    phrase: "extend a deadline",
    meaning: "締め切りを延長する",
    example: "The client agreed to extend the deadline by two weeks.",
    exampleTranslation: "顧客は締め切りを2週間延長することに同意した。",
    note: "extend は「延ばす」。extend an invitation（招待する）という使い方もある。",
  },
  {
    id: "ph-vn-11",
    category: "verb-noun",
    phrase: "fill a vacancy",
    meaning: "欠員を補充する",
    example: "The department hopes to fill the vacancy by the end of the month.",
    exampleTranslation: "その部署は月末までに欠員を補充したいと考えている。",
    note: "vacancy は「欠員・空室」。求人票やホテルの文脈で出る。",
  },
  {
    id: "ph-vn-12",
    category: "verb-noun",
    phrase: "process an application",
    meaning: "申請を処理する",
    example: "It normally takes ten days to process an application.",
    exampleTranslation: "申請の処理には通常10日かかる。",
  },
  {
    id: "ph-vn-13",
    category: "verb-noun",
    phrase: "meet expectations",
    meaning: "期待に応える",
    example: "Fourth-quarter sales did not meet expectations.",
    exampleTranslation: "第4四半期の売上は期待に届かなかった。",
    note: "「期待を上回る」は exceed expectations、「下回る」は fall short of expectations。",
  },
  {
    id: "ph-vn-14",
    category: "verb-noun",
    phrase: "cut costs",
    meaning: "経費を削減する",
    example: "Switching suppliers helped the plant cut costs by 18 percent.",
    exampleTranslation: "仕入先を変えたことで、その工場は経費を18パーセント削減できた。",
    note: "硬い言い方なら reduce costs。「経費削減策」は cost-cutting measures。",
  },
  {
    id: "ph-vn-15",
    category: "verb-noun",
    phrase: "launch a product",
    meaning: "製品を発売する",
    example: "The company will launch its new tablet in September.",
    exampleTranslation: "その会社は9月に新型タブレットを発売する。",
    note: "名詞でも使い、product launch は「製品発表・発売」。",
  },
  {
    id: "ph-vn-16",
    category: "verb-noun",
    phrase: "renew a contract",
    meaning: "契約を更新する",
    example: "We decided not to renew the maintenance contract.",
    exampleTranslation: "保守契約は更新しないことにした。",
    note: "renew a subscription（定期購読を更新する）、renew a license も同じ形。",
  },
  {
    id: "ph-vn-17",
    category: "verb-noun",
    phrase: "settle an invoice",
    meaning: "請求書の支払いを済ませる",
    example: "All invoices must be settled within 30 days.",
    exampleTranslation: "請求書はすべて30日以内に支払わなければならない。",
    note: "settle は「（勘定を）清算する」。settle a dispute なら「紛争を解決する」。",
  },
  {
    id: "ph-vn-18",
    category: "verb-noun",
    phrase: "draw up a contract",
    meaning: "契約書を作成する",
    example: "The legal team will draw up a contract by Thursday.",
    exampleTranslation: "法務チームが木曜日までに契約書を作成する。",
    note: "draw up は「（書類を）作成する」。draw up a plan も使う。",
  },
  {
    id: "ph-vn-19",
    category: "verb-noun",
    phrase: "streamline a process",
    meaning: "工程を効率化する",
    example: "The new software streamlined the approval process considerably.",
    exampleTranslation: "新しいソフトにより承認手続きが大幅に効率化された。",
    note: "streamline は「無駄を省いて簡素にする」。業務改善の話題で頻出。",
  },
  {
    id: "ph-vn-20",
    category: "verb-noun",
    phrase: "submit a proposal",
    meaning: "提案書を提出する",
    example: "Bidders must submit a proposal by 5:00 P.M. on 30 June.",
    exampleTranslation: "入札者は6月30日午後5時までに提案書を提出すること。",
  },
  {
    id: "ph-vn-21",
    category: "verb-noun",
    phrase: "hold a position",
    meaning: "職に就いている",
    example: "Ms. Ortega held the position of chief engineer for eight years.",
    exampleTranslation: "オルテガさんは8年間、主任技師の職にあった。",
    note: "hold a meeting（会議を開く）と同じ動詞だが意味が違うので文脈で判断する。",
  },
  {
    id: "ph-vn-22",
    category: "verb-noun",
    phrase: "raise a concern",
    meaning: "懸念を提起する",
    example: "Several residents raised concerns about the noise levels.",
    exampleTranslation: "複数の住民が騒音について懸念を示した。",
    note: "raise は「（話題・問題を）持ち出す」。raise a question も同じ形。",
  },
  {
    id: "ph-vn-23",
    category: "verb-noun",
    phrase: "meet the requirements",
    meaning: "要件を満たす",
    example: "Only two of the applicants met the requirements for the post.",
    exampleTranslation: "応募者のうち2名だけがその職の要件を満たしていた。",
  },
  {
    id: "ph-vn-24",
    category: "verb-noun",
    phrase: "make an appointment",
    meaning: "面会や診察の予約を取る",
    example: "Please make an appointment before visiting the clinic.",
    exampleTranslation: "来院前にご予約をお取りください。",
    note: "人と会う予約は appointment、座席や部屋の予約は reservation。",
  },
  {
    id: "ph-vn-25",
    category: "verb-noun",
    phrase: "take inventory",
    meaning: "棚卸しをする",
    example: "The store closes early on the last Friday to take inventory.",
    exampleTranslation: "その店は棚卸しのため、最終金曜日は早じまいする。",
    note: "inventory は「在庫、在庫目録」。be out of stock（在庫切れ）とあわせて覚える。",
  },

  // ------------------------------------------------------------------
  // 動詞＋前置詞（verb-prep）
  // ------------------------------------------------------------------
  {
    id: "ph-vp-01",
    category: "verb-prep",
    phrase: "comply with",
    meaning: "（規則などに）従う",
    example: "All contractors must comply with the site safety rules.",
    exampleTranslation: "請負業者は全員、現場の安全規則に従わなければならない。",
    note: "with が必須。obey と follow は前置詞なしで目的語を取る点が違う。",
  },
  {
    id: "ph-vp-02",
    category: "verb-prep",
    phrase: "adhere to",
    meaning: "（規範などを）守る",
    example: "Staff are expected to adhere to the code of conduct.",
    exampleTranslation: "職員は行動規範を遵守することが求められている。",
    note: "comply with より硬い言い方。to のあとは名詞か動名詞。",
  },
  {
    id: "ph-vp-03",
    category: "verb-prep",
    phrase: "account for",
    meaning: "①〜を説明する ②〜を占める",
    example: "Online sales account for nearly half of the company's revenue.",
    exampleTranslation: "オンライン販売が同社の売上のほぼ半分を占めている。",
    note: "2つの意味があり、数字が続けば「占める」、理由が続けば「説明する」。",
  },
  {
    id: "ph-vp-04",
    category: "verb-prep",
    phrase: "refrain from",
    meaning: "〜を控える",
    example: "Visitors are asked to refrain from using mobile phones in the gallery.",
    exampleTranslation: "展示室内での携帯電話のご使用はお控えください。",
    note: "from のあとは動名詞。掲示文で「ご遠慮ください」に当たる表現。",
  },
  {
    id: "ph-vp-05",
    category: "verb-prep",
    phrase: "result in",
    meaning: "（結果として）〜をもたらす",
    example: "The power failure resulted in a two-hour delay.",
    exampleTranslation: "停電により2時間の遅れが生じた。",
    note: "向きが逆の result from は「〜が原因で起こる」。取り違えに注意。",
  },
  {
    id: "ph-vp-06",
    category: "verb-prep",
    phrase: "cope with",
    meaning: "（困難に）対処する",
    example: "Extra staff were hired to cope with the seasonal demand.",
    exampleTranslation: "季節的な需要に対応するため、臨時職員が雇われた。",
  },
  {
    id: "ph-vp-07",
    category: "verb-prep",
    phrase: "cater to",
    meaning: "〜の需要に応える、〜向けである",
    example: "The hotel caters to business travellers.",
    exampleTranslation: "そのホテルはビジネス客向けである。",
    note: "cater for という形もある。「（食事を）仕出しする」の意味も持つ。",
  },
  {
    id: "ph-vp-08",
    category: "verb-prep",
    phrase: "subscribe to",
    meaning: "〜を定期購読する、〜に加入する",
    example: "More than 20,000 readers subscribe to the newsletter.",
    exampleTranslation: "2万人を超える読者がそのニュースレターを購読している。",
  },
  {
    id: "ph-vp-09",
    category: "verb-prep",
    phrase: "enroll in",
    meaning: "（講座などに）登録する",
    example: "Employees may enroll in the training course at no cost.",
    exampleTranslation: "従業員は無料でその研修講座に申し込める。",
    note: "「登録させる」は enroll A in B。名詞は enrollment。",
  },
  {
    id: "ph-vp-10",
    category: "verb-prep",
    phrase: "specialize in",
    meaning: "〜を専門とする",
    example: "The firm specializes in cold-chain logistics.",
    exampleTranslation: "その会社は低温物流を専門としている。",
  },
  {
    id: "ph-vp-11",
    category: "verb-prep",
    phrase: "apply for",
    meaning: "〜に応募する、〜を申請する",
    example: "Candidates should apply for the position online.",
    exampleTranslation: "応募者はその職にオンラインで応募すること。",
    note: "apply to は「〜に当てはまる」。The rule applies to all staff. と区別する。",
  },
  {
    id: "ph-vp-12",
    category: "verb-prep",
    phrase: "consist of",
    meaning: "〜から成る",
    example: "The panel consists of five external experts.",
    exampleTranslation: "その委員会は5名の外部専門家で構成されている。",
    note: "受動態にはしない。be consisted of は誤り。",
  },
  {
    id: "ph-vp-13",
    category: "verb-prep",
    phrase: "depend on",
    meaning: "〜次第である、〜に頼る",
    example: "The completion date depends on when the permits are issued.",
    exampleTranslation: "完成時期は許可がいつ下りるかによる。",
  },
  {
    id: "ph-vp-14",
    category: "verb-prep",
    phrase: "refer to",
    meaning: "〜を参照する、〜に言及する",
    example: "Please refer to page 12 for the full specifications.",
    exampleTranslation: "詳細な仕様は12ページをご参照ください。",
    note: "refer A to B なら「AをBに差し向ける」。",
  },
  {
    id: "ph-vp-15",
    category: "verb-prep",
    phrase: "follow up on",
    meaning: "〜を追って確認する",
    example: "I am writing to follow up on my e-mail of 3 May.",
    exampleTranslation: "5月3日のメールの件で、その後の確認のためご連絡しています。",
    note: "メールの書き出しで頻出。名詞は follow-up。",
  },
  {
    id: "ph-vp-16",
    category: "verb-prep",
    phrase: "opt for",
    meaning: "〜を選ぶ",
    example: "Most customers opt for the extended warranty.",
    exampleTranslation: "大半の顧客が延長保証を選んでいる。",
    note: "「〜しないことにする」は opt out of。",
  },
  {
    id: "ph-vp-17",
    category: "verb-prep",
    phrase: "benefit from",
    meaning: "〜から恩恵を受ける",
    example: "Small suppliers will benefit from the simplified process.",
    exampleTranslation: "小規模な仕入先は、簡素化された手続きの恩恵を受けるだろう。",
  },
  {
    id: "ph-vp-18",
    category: "verb-prep",
    phrase: "contribute to",
    meaning: "〜に貢献する、〜の一因となる",
    example: "Poor signage contributed to the confusion at the entrance.",
    exampleTranslation: "案内表示の不備が入口での混乱の一因となった。",
    note: "良い意味にも悪い意味にも使える点に注意。",
  },
  {
    id: "ph-vp-19",
    category: "verb-prep",
    phrase: "object to",
    meaning: "〜に反対する",
    example: "Two board members objected to the proposed merger.",
    exampleTranslation: "取締役2名が合併案に反対した。",
    note: "to は前置詞なので、うしろに動詞が来るときは動名詞になる。",
  },
  {
    id: "ph-vp-20",
    category: "verb-prep",
    phrase: "respond to",
    meaning: "〜に返答する、〜に対応する",
    example: "We aim to respond to all inquiries within 24 hours.",
    exampleTranslation: "すべての問い合わせに24時間以内に回答することを目指しています。",
  },
  {
    id: "ph-vp-21",
    category: "verb-prep",
    phrase: "dispose of",
    meaning: "〜を処分する",
    example: "Used batteries must be disposed of at a collection point.",
    exampleTranslation: "使用済み電池は回収拠点で処分しなければならない。",
    note: "受動態にしても of が残る。be disposed of の形を覚えておく。",
  },
  {
    id: "ph-vp-22",
    category: "verb-prep",
    phrase: "participate in",
    meaning: "〜に参加する",
    example: "Over 300 employees participated in the wellness programme.",
    exampleTranslation: "300名を超える従業員が健康増進プログラムに参加した。",
    note: "attend は前置詞なしで目的語を取る（attend a meeting）。",
  },
  {
    id: "ph-vp-23",
    category: "verb-prep",
    phrase: "look into",
    meaning: "〜を調査する",
    example: "The supervisor promised to look into the billing error.",
    exampleTranslation: "上司は請求の誤りを調べると約束した。",
    note: "investigate のくだけた言い方。look over なら「ざっと目を通す」。",
  },
  {
    id: "ph-vp-24",
    category: "verb-prep",
    phrase: "check in with",
    meaning: "〜に状況を確認する",
    example: "I will check in with the vendor before the end of the day.",
    exampleTranslation: "本日中に業者へ状況を確認します。",
    note: "check in は「宿泊や搭乗の手続きをする」の意味でも出る。",
  },
  {
    id: "ph-vp-25",
    category: "verb-prep",
    phrase: "fill out",
    meaning: "（書類に）記入する",
    example: "Please fill out the form and return it to reception.",
    exampleTranslation: "用紙にご記入のうえ、受付にご返却ください。",
    note: "fill in も同じ意味で使われる。fill up は「満タンにする」。",
  },

  // ------------------------------------------------------------------
  // 形容詞＋前置詞（adj-prep）
  // ------------------------------------------------------------------
  {
    id: "ph-ap-01",
    category: "adj-prep",
    phrase: "be eligible for",
    meaning: "〜の資格がある",
    example: "Staff are eligible for the bonus after one year of service.",
    exampleTranslation: "職員は勤続1年で賞与の対象となる。",
    note: "うしろに動詞を置くときは be eligible to do の形にする。",
  },
  {
    id: "ph-ap-02",
    category: "adj-prep",
    phrase: "be responsible for",
    meaning: "〜に責任がある、〜を担当している",
    example: "Ms. Vargas is responsible for supplier relations.",
    exampleTranslation: "バルガスさんは仕入先との関係を担当している。",
    note: "in charge of もほぼ同じ意味で言い換えに使われる。",
  },
  {
    id: "ph-ap-03",
    category: "adj-prep",
    phrase: "be liable for",
    meaning: "〜に対して法的責任を負う",
    example: "The carrier is liable for damage in transit.",
    exampleTranslation: "運送業者は輸送中の損傷について責任を負う。",
    note: "be liable to do は「〜しがちである」で意味が変わる。",
  },
  {
    id: "ph-ap-04",
    category: "adj-prep",
    phrase: "be subject to",
    meaning: "〜を条件とする、〜を受けやすい",
    example: "Prices are subject to change without notice.",
    exampleTranslation: "価格は予告なく変更されることがあります。",
    note: "この to は前置詞。広告やカタログの注記で頻出する。",
  },
  {
    id: "ph-ap-05",
    category: "adj-prep",
    phrase: "be committed to",
    meaning: "〜に力を注いでいる",
    example: "The firm is committed to reducing its packaging waste.",
    exampleTranslation: "その会社は包装廃棄物の削減に力を入れている。",
    note: "to は前置詞なので、うしろの動詞は動名詞になる。",
  },
  {
    id: "ph-ap-06",
    category: "adj-prep",
    phrase: "be accustomed to",
    meaning: "〜に慣れている",
    example: "New hires soon become accustomed to the reporting system.",
    exampleTranslation: "新入社員はすぐに報告システムに慣れる。",
    note: "be used to と同じく、to のあとは動名詞。",
  },
  {
    id: "ph-ap-07",
    category: "adj-prep",
    phrase: "be familiar with",
    meaning: "〜をよく知っている",
    example: "Applicants should be familiar with spreadsheet software.",
    exampleTranslation: "応募者は表計算ソフトに習熟していることが望ましい。",
    note: "be familiar to なら「〜にとってなじみがある」で主語が入れ替わる。",
  },
  {
    id: "ph-ap-08",
    category: "adj-prep",
    phrase: "be consistent with",
    meaning: "〜と一致している",
    example: "The results are consistent with last year's findings.",
    exampleTranslation: "その結果は昨年の調査結果と一致している。",
  },
  {
    id: "ph-ap-09",
    category: "adj-prep",
    phrase: "be compatible with",
    meaning: "〜と互換性がある",
    example: "The printer is compatible with all current operating systems.",
    exampleTranslation: "そのプリンターは現行のすべての OS に対応している。",
  },
  {
    id: "ph-ap-10",
    category: "adj-prep",
    phrase: "be capable of",
    meaning: "〜する能力がある",
    example: "The machine is capable of producing 400 units per hour.",
    exampleTranslation: "その機械は1時間に400個を生産できる。",
    note: "of は前置詞なので、うしろは動名詞。be able to do とは形が違う。",
  },
  {
    id: "ph-ap-11",
    category: "adj-prep",
    phrase: "be exempt from",
    meaning: "〜を免除されている",
    example: "Nonprofit organizations are exempt from the registration fee.",
    exampleTranslation: "非営利団体は登録料を免除される。",
  },
  {
    id: "ph-ap-12",
    category: "adj-prep",
    phrase: "be entitled to",
    meaning: "〜を受ける権利がある",
    example: "Full-time staff are entitled to 20 days of paid leave.",
    exampleTranslation: "常勤職員は20日の有給休暇を取得する権利がある。",
    note: "be eligible for と意味は近いが、entitle は「権利を与える」というニュアンス。",
  },
  {
    id: "ph-ap-13",
    category: "adj-prep",
    phrase: "be dependent on",
    meaning: "〜に左右される",
    example: "The schedule is dependent on the arrival of the components.",
    exampleTranslation: "日程は部品の到着に左右される。",
  },
  {
    id: "ph-ap-14",
    category: "adj-prep",
    phrase: "be relevant to",
    meaning: "〜に関係がある",
    example: "Only documents relevant to the claim should be attached.",
    exampleTranslation: "請求に関係のある書類のみを添付してください。",
  },
  {
    id: "ph-ap-15",
    category: "adj-prep",
    phrase: "be comparable to",
    meaning: "〜に匹敵する",
    example: "The new model's output is comparable to that of larger units.",
    exampleTranslation: "新型の出力は、より大型の機種に匹敵する。",
  },
  {
    id: "ph-ap-16",
    category: "adj-prep",
    phrase: "be reluctant to",
    meaning: "〜したがらない",
    example: "The supplier was reluctant to revise the delivery schedule.",
    exampleTranslation: "その仕入先は納品日程の見直しに消極的だった。",
    note: "この to は不定詞なので、うしろは動詞の原形。",
  },
  {
    id: "ph-ap-17",
    category: "adj-prep",
    phrase: "be short of",
    meaning: "〜が不足している",
    example: "The warehouse is short of trained forklift operators.",
    exampleTranslation: "その倉庫では、訓練を受けたフォークリフト操作者が不足している。",
    note: "fall short of なら「（基準に）届かない」。",
  },
  {
    id: "ph-ap-18",
    category: "adj-prep",
    phrase: "be prone to",
    meaning: "〜しやすい、〜の傾向がある",
    example: "Older units are prone to overheating in summer.",
    exampleTranslation: "旧型の機器は夏場に過熱しやすい。",
  },
  {
    id: "ph-ap-19",
    category: "adj-prep",
    phrase: "be applicable to",
    meaning: "〜に適用される",
    example: "The discount is applicable to online purchases only.",
    exampleTranslation: "その割引はオンライン購入のみに適用される。",
  },
  {
    id: "ph-ap-20",
    category: "adj-prep",
    phrase: "be equipped with",
    meaning: "〜を備えている",
    example: "Every meeting room is equipped with video-conferencing gear.",
    exampleTranslation: "すべての会議室にはテレビ会議設備が備わっている。",
  },
  {
    id: "ph-ap-21",
    category: "adj-prep",
    phrase: "be satisfied with",
    meaning: "〜に満足している",
    example: "Ninety percent of respondents were satisfied with the service.",
    exampleTranslation: "回答者の90パーセントがそのサービスに満足していた。",
  },
  {
    id: "ph-ap-22",
    category: "adj-prep",
    phrase: "be aware of",
    meaning: "〜に気づいている、〜を承知している",
    example: "Please be aware of the revised opening hours.",
    exampleTranslation: "営業時間の変更にご留意ください。",
  },
  {
    id: "ph-ap-23",
    category: "adj-prep",
    phrase: "be indicative of",
    meaning: "〜を示している",
    example: "The drop in inquiries is indicative of a wider slowdown.",
    exampleTranslation: "問い合わせの減少は、より広い景気減速を示している。",
    note: "硬い表現。記事やレポートの文で出る。",
  },
  {
    id: "ph-ap-24",
    category: "adj-prep",
    phrase: "be conducive to",
    meaning: "〜のためになる、〜を促す",
    example: "Natural light is conducive to concentration.",
    exampleTranslation: "自然光は集中を促す。",
    note: "to は前置詞。うしろに動詞が来れば動名詞になる。",
  },
  {
    id: "ph-ap-25",
    category: "adj-prep",
    phrase: "be renowned for",
    meaning: "〜で有名である",
    example: "The region is renowned for its textile industry.",
    exampleTranslation: "その地域は繊維産業で知られている。",
    note: "be known for、be famous for も同じ形で使える。",
  },

  // ------------------------------------------------------------------
  // 前置詞句・副詞句（prep-phrase）
  // ------------------------------------------------------------------
  {
    id: "ph-pp-01",
    category: "prep-phrase",
    phrase: "in accordance with",
    meaning: "〜に従って",
    example: "Waste is handled in accordance with local regulations.",
    exampleTranslation: "廃棄物は地域の規則に従って処理される。",
    note: "契約書や通知文で頻出。according to は「〜によれば」で意味が違う。",
  },
  {
    id: "ph-pp-02",
    category: "prep-phrase",
    phrase: "on behalf of",
    meaning: "〜を代表して、〜に代わって",
    example: "On behalf of the whole team, thank you for your support.",
    exampleTranslation: "チーム一同を代表して、ご支援に感謝いたします。",
  },
  {
    id: "ph-pp-03",
    category: "prep-phrase",
    phrase: "in advance",
    meaning: "前もって",
    example: "Please notify the office at least two days in advance.",
    exampleTranslation: "遅くとも2日前までに事務所へご連絡ください。",
    note: "in advance of ... なら「〜に先立って」。",
  },
  {
    id: "ph-pp-04",
    category: "prep-phrase",
    phrase: "in lieu of",
    meaning: "〜の代わりに",
    example: "Staff may take time off in lieu of overtime pay.",
    exampleTranslation: "職員は残業代の代わりに代休を取ることができる。",
    note: "instead of の硬い言い方。人事関連の文書で出る。",
  },
  {
    id: "ph-pp-05",
    category: "prep-phrase",
    phrase: "in the event of",
    meaning: "〜の場合には",
    example: "In the event of a power failure, use the stairwell.",
    exampleTranslation: "停電の場合は階段をご利用ください。",
    note: "うしろが文なら in the event that ... になる。",
  },
  {
    id: "ph-pp-06",
    category: "prep-phrase",
    phrase: "with regard to",
    meaning: "〜に関して",
    example: "I am writing with regard to invoice 2210.",
    exampleTranslation: "請求書2210の件でご連絡しております。",
    note: "regarding、concerning も同じ意味で1語の前置詞として使える。",
  },
  {
    id: "ph-pp-07",
    category: "prep-phrase",
    phrase: "owing to",
    meaning: "〜のために（原因）",
    example: "The ferry was cancelled owing to high winds.",
    exampleTranslation: "強風のため、そのフェリーは欠航した。",
    note: "due to、because of も同義。うしろは必ず名詞句。",
  },
  {
    id: "ph-pp-08",
    category: "prep-phrase",
    phrase: "in light of",
    meaning: "〜を踏まえて",
    example: "In light of the survey results, the policy was revised.",
    exampleTranslation: "調査結果を踏まえ、その方針は見直された。",
  },
  {
    id: "ph-pp-09",
    category: "prep-phrase",
    phrase: "as of",
    meaning: "〜付けで、〜の時点で",
    example: "As of 1 July, all invoices go through the Finance Hub.",
    exampleTranslation: "7月1日付けで、請求書はすべて Finance Hub 経由となる。",
  },
  {
    id: "ph-pp-10",
    category: "prep-phrase",
    phrase: "at the latest",
    meaning: "遅くとも",
    example: "Submit the form by Friday at the latest.",
    exampleTranslation: "遅くとも金曜日までに用紙を提出してください。",
    note: "反対は at the earliest（早くても）。",
  },
  {
    id: "ph-pp-11",
    category: "prep-phrase",
    phrase: "on short notice",
    meaning: "急な連絡で、直前に",
    example: "Thank you for covering the shift on short notice.",
    exampleTranslation: "急なお願いにもかかわらずシフトに入っていただき、ありがとうございます。",
    note: "イギリス英語では at short notice の形も使われる。",
  },
  {
    id: "ph-pp-12",
    category: "prep-phrase",
    phrase: "ahead of schedule",
    meaning: "予定より早く",
    example: "The renovation was completed ahead of schedule.",
    exampleTranslation: "改修工事は予定より早く完了した。",
    note: "反対は behind schedule（予定より遅れて）、ちょうどなら on schedule。",
  },
  {
    id: "ph-pp-13",
    category: "prep-phrase",
    phrase: "in bulk",
    meaning: "大量に、まとめて",
    example: "Restaurants can order napkins in bulk at a lower rate.",
    exampleTranslation: "飲食店は紙ナプキンをまとめて安く注文できる。",
  },
  {
    id: "ph-pp-14",
    category: "prep-phrase",
    phrase: "in person",
    meaning: "直接、本人が出向いて",
    example: "Applications must be submitted in person at the front desk.",
    exampleTranslation: "申請は受付に直接お持ちください。",
  },
  {
    id: "ph-pp-15",
    category: "prep-phrase",
    phrase: "in writing",
    meaning: "書面で",
    example: "Any complaint must be made in writing within 14 days.",
    exampleTranslation: "苦情は14日以内に書面で申し出なければならない。",
  },
  {
    id: "ph-pp-16",
    category: "prep-phrase",
    phrase: "on site",
    meaning: "現場で、敷地内で",
    example: "A qualified engineer is on site during working hours.",
    exampleTranslation: "就業時間中は有資格の技術者が現場に常駐している。",
    note: "反対は off site。形容詞として on-site parking のようにも使う。",
  },
  {
    id: "ph-pp-17",
    category: "prep-phrase",
    phrase: "out of stock",
    meaning: "在庫切れで",
    example: "The item you requested is temporarily out of stock.",
    exampleTranslation: "ご希望の商品は一時的に在庫を切らしております。",
    note: "在庫ありは in stock。入荷待ちは on back order。",
  },
  {
    id: "ph-pp-18",
    category: "prep-phrase",
    phrase: "under warranty",
    meaning: "保証期間中で",
    example: "Repairs are free of charge while the unit is under warranty.",
    exampleTranslation: "保証期間中であれば修理は無料である。",
  },
  {
    id: "ph-pp-19",
    category: "prep-phrase",
    phrase: "under way",
    meaning: "進行中で",
    example: "Renovation of the east wing is currently under way.",
    exampleTranslation: "東棟の改修は現在進行中である。",
    note: "get under way なら「始まる」。",
  },
  {
    id: "ph-pp-20",
    category: "prep-phrase",
    phrase: "within walking distance",
    meaning: "徒歩圏内に",
    example: "The venue is within walking distance of the station.",
    exampleTranslation: "会場は駅から徒歩圏内にある。",
    note: "続く前置詞は of。広告文で頻出。",
  },
  {
    id: "ph-pp-21",
    category: "prep-phrase",
    phrase: "free of charge",
    meaning: "無料で",
    example: "Delivery is free of charge on orders over 50 dollars.",
    exampleTranslation: "50ドルを超えるご注文は配送無料です。",
    note: "at no extra cost（追加料金なしで）とあわせて覚える。",
  },
  {
    id: "ph-pp-22",
    category: "prep-phrase",
    phrase: "upon receipt",
    meaning: "受領次第",
    example: "Payment is due upon receipt of the invoice.",
    exampleTranslation: "支払いは請求書の受領をもって期日となる。",
  },
  {
    id: "ph-pp-23",
    category: "prep-phrase",
    phrase: "no later than",
    meaning: "遅くとも〜までに",
    example: "Confirm your attendance no later than 18 April.",
    exampleTranslation: "4月18日までに出席のご確認をお願いします。",
  },
  {
    id: "ph-pp-24",
    category: "prep-phrase",
    phrase: "in compliance with",
    meaning: "〜を遵守して",
    example: "The building was designed in compliance with fire codes.",
    exampleTranslation: "その建物は消防法規に適合して設計された。",
  },
  {
    id: "ph-pp-25",
    category: "prep-phrase",
    phrase: "at your earliest convenience",
    meaning: "ご都合のつき次第、なるべく早く",
    example: "Please return the signed form at your earliest convenience.",
    exampleTranslation: "署名済みの用紙を、ご都合のつき次第ご返送ください。",
    note: "丁寧に急かす定型。メールの結びで頻出。",
  },

  // ------------------------------------------------------------------
  // ビジネス定型表現（business）
  // ------------------------------------------------------------------
  {
    id: "ph-bz-01",
    category: "business",
    phrase: "Please be advised that ...",
    meaning: "〜をお知らせいたします",
    example: "Please be advised that the car park will be closed on Sunday.",
    exampleTranslation: "日曜日は駐車場が閉鎖されますのでお知らせいたします。",
    note: "掲示や社内通知の書き出し。Part 7 のお知らせ文で頻出。",
  },
  {
    id: "ph-bz-02",
    category: "business",
    phrase: "Attached please find ...",
    meaning: "〜を添付いたします",
    example: "Attached please find the revised floor plan.",
    exampleTranslation: "修正した配置図を添付いたします。",
    note: "Please find attached ... の語順でも使われる。",
  },
  {
    id: "ph-bz-03",
    category: "business",
    phrase: "Should you have any questions, ...",
    meaning: "ご不明な点がございましたら",
    example: "Should you have any questions, please contact the help desk.",
    exampleTranslation: "ご不明な点がございましたら、ヘルプデスクへご連絡ください。",
    note: "If you should have ... の if を省いた倒置。Part 5 でも問われる形。",
  },
  {
    id: "ph-bz-04",
    category: "business",
    phrase: "We regret to inform you that ...",
    meaning: "残念ながら〜をお知らせします",
    example: "We regret to inform you that your application was unsuccessful.",
    exampleTranslation: "残念ながら、ご応募は不採用となりましたことをお知らせします。",
    note: "不採用通知や欠航案内の定型。良い知らせなら We are pleased to inform you。",
  },
  {
    id: "ph-bz-05",
    category: "business",
    phrase: "Thank you for your patience",
    meaning: "お待たせして申し訳ありません",
    example: "Thank you for your patience while we upgrade the system.",
    exampleTranslation: "システム更新の間お待たせし、申し訳ありません。",
    note: "直訳の「辛抱に感謝」ではなく、遅延のお詫びとして使う。",
  },
  {
    id: "ph-bz-06",
    category: "business",
    phrase: "as requested",
    meaning: "ご依頼のとおり",
    example: "As requested, I have enclosed three references.",
    exampleTranslation: "ご依頼のとおり、推薦者3名分を同封しました。",
  },
  {
    id: "ph-bz-07",
    category: "business",
    phrase: "effective immediately",
    meaning: "即日発効で",
    example: "Effective immediately, all visitors must sign in at reception.",
    exampleTranslation: "本日より、来訪者は全員受付での記帳が必要です。",
    note: "effective +日付で「〜から有効」。effective 1 July のようにも使う。",
  },
  {
    id: "ph-bz-08",
    category: "business",
    phrase: "pending approval",
    meaning: "承認待ちで",
    example: "The budget increase is pending approval by the board.",
    exampleTranslation: "増額分は取締役会の承認待ちである。",
    note: "pending は「保留中の」という形容詞でも、「〜まで」という前置詞でも使う。",
  },
  {
    id: "ph-bz-09",
    category: "business",
    phrase: "subject to change without notice",
    meaning: "予告なく変更されることがあります",
    example: "Timetables are subject to change without notice.",
    exampleTranslation: "時刻表は予告なく変更されることがあります。",
  },
  {
    id: "ph-bz-10",
    category: "business",
    phrase: "We look forward to hearing from you",
    meaning: "ご連絡をお待ちしております",
    example: "We look forward to hearing from you before the end of the month.",
    exampleTranslation: "月末までにご連絡いただけますようお待ちしております。",
    note: "to は前置詞なので hearing と動名詞になる。Part 5 でも狙われる。",
  },
  {
    id: "ph-bz-11",
    category: "business",
    phrase: "until further notice",
    meaning: "追って通知があるまで",
    example: "The north entrance is closed until further notice.",
    exampleTranslation: "北口は追って通知があるまで閉鎖されます。",
  },
  {
    id: "ph-bz-12",
    category: "business",
    phrase: "in the meantime",
    meaning: "その間に、それまでは",
    example: "The new portal opens in June. In the meantime, use the old form.",
    exampleTranslation: "新しいポータルは6月開設です。それまでは旧様式をご利用ください。",
  },
  {
    id: "ph-bz-13",
    category: "business",
    phrase: "please disregard",
    meaning: "破棄してください、無視してください",
    example: "If you have already paid, please disregard this reminder.",
    exampleTranslation: "お支払い済みの場合は、この督促を破棄してください。",
  },
  {
    id: "ph-bz-14",
    category: "business",
    phrase: "at no extra cost",
    meaning: "追加料金なしで",
    example: "Gift wrapping is available at no extra cost.",
    exampleTranslation: "贈答用の包装は追加料金なしでご利用いただけます。",
  },
  {
    id: "ph-bz-15",
    category: "business",
    phrase: "on a first-come, first-served basis",
    meaning: "先着順で",
    example: "Seats are allocated on a first-come, first-served basis.",
    exampleTranslation: "席は先着順で割り当てられます。",
    note: "on a ... basis は「〜の方式で」。on a weekly basis なら「毎週」。",
  },
  {
    id: "ph-bz-16",
    category: "business",
    phrase: "be scheduled to",
    meaning: "〜する予定である",
    example: "The auditors are scheduled to arrive on Monday morning.",
    exampleTranslation: "監査人は月曜日の朝に到着する予定である。",
    note: "be due to、be set to もほぼ同じ意味で言い換えに使われる。",
  },
  {
    id: "ph-bz-17",
    category: "business",
    phrase: "keep someone posted",
    meaning: "〜に随時知らせる",
    example: "I will keep you posted on the status of the shipment.",
    exampleTranslation: "積荷の状況については随時お知らせします。",
    note: "keep someone informed も同じ意味。",
  },
  {
    id: "ph-bz-18",
    category: "business",
    phrase: "touch base with",
    meaning: "〜と連絡を取る",
    example: "Let me touch base with the vendor before we decide.",
    exampleTranslation: "決定する前に、業者と連絡を取らせてください。",
    note: "話し言葉寄りの表現。Part 3 や社内メールに出る。",
  },
  {
    id: "ph-bz-19",
    category: "business",
    phrase: "run behind",
    meaning: "予定より遅れている",
    example: "We are running behind, so the demo will start at 3:15.",
    exampleTranslation: "予定より遅れているため、実演は3時15分開始とします。",
  },
  {
    id: "ph-bz-20",
    category: "business",
    phrase: "fill in for",
    meaning: "〜の代わりを務める",
    example: "Ms. Cole will fill in for the department head next week.",
    exampleTranslation: "来週はコールさんが部長の代理を務める。",
    note: "cover for も同じ意味で使われる。",
  },
  {
    id: "ph-bz-21",
    category: "business",
    phrase: "come into effect",
    meaning: "発効する",
    example: "The new parking rules come into effect next Monday.",
    exampleTranslation: "新しい駐車規則は来週月曜日から実施される。",
  },
  {
    id: "ph-bz-22",
    category: "business",
    phrase: "in the pipeline",
    meaning: "準備中で、進行中で",
    example: "Two more distribution centres are in the pipeline.",
    exampleTranslation: "配送センターがさらに2か所、計画進行中である。",
  },
  {
    id: "ph-bz-23",
    category: "business",
    phrase: "get back to someone",
    meaning: "〜に折り返し連絡する",
    example: "I will get back to you once I have confirmed the figures.",
    exampleTranslation: "数字を確認したうえで、折り返しご連絡します。",
  },
  {
    id: "ph-bz-24",
    category: "business",
    phrase: "take over",
    meaning: "（業務・職務を）引き継ぐ",
    example: "Mr. Novak will take over the account in October.",
    exampleTranslation: "10月からノバクさんがその取引先を引き継ぐ。",
    note: "take over from someone で「〜から引き継ぐ」。企業の「買収」の意味もある。",
  },
  {
    id: "ph-bz-25",
    category: "business",
    phrase: "be up and running",
    meaning: "（設備などが）稼働している",
    example: "The replacement server should be up and running by noon.",
    exampleTranslation: "交換したサーバーは正午までに稼働する見込みである。",
  },

  // ------------------------------------------------------------------
  // 名詞句・複合名詞（noun-phrase）
  // ------------------------------------------------------------------
  {
    id: "ph-np-01",
    category: "noun-phrase",
    phrase: "purchase order",
    meaning: "発注書",
    example: "Suppliers must quote the purchase order number on all invoices.",
    exampleTranslation: "仕入先はすべての請求書に発注番号を記載すること。",
    note: "略して PO。invoice（請求書）、receipt（領収書）と区別する。",
  },
  {
    id: "ph-np-02",
    category: "noun-phrase",
    phrase: "expiration date",
    meaning: "有効期限",
    example: "Check the expiration date before using the coupon.",
    exampleTranslation: "クーポンをご使用の前に有効期限をご確認ください。",
    note: "イギリス英語では expiry date。",
  },
  {
    id: "ph-np-03",
    category: "noun-phrase",
    phrase: "warranty period",
    meaning: "保証期間",
    example: "The warranty period begins on the date of delivery.",
    exampleTranslation: "保証期間は納品日から始まる。",
  },
  {
    id: "ph-np-04",
    category: "noun-phrase",
    phrase: "job opening",
    meaning: "求人、欠員",
    example: "There are two job openings in the logistics team.",
    exampleTranslation: "物流チームに2件の求人がある。",
    note: "job vacancy、position ともほぼ同義。",
  },
  {
    id: "ph-np-05",
    category: "noun-phrase",
    phrase: "performance review",
    meaning: "人事評価、業績評価",
    example: "Performance reviews take place every six months.",
    exampleTranslation: "人事評価は半年ごとに実施される。",
    note: "performance appraisal とも言う。",
  },
  {
    id: "ph-np-06",
    category: "noun-phrase",
    phrase: "board of directors",
    meaning: "取締役会",
    example: "The board of directors meets on the first Tuesday of each month.",
    exampleTranslation: "取締役会は毎月第1火曜日に開かれる。",
  },
  {
    id: "ph-np-07",
    category: "noun-phrase",
    phrase: "point of contact",
    meaning: "窓口、連絡担当者",
    example: "Ms. Ibrahim will be your main point of contact during the project.",
    exampleTranslation: "プロジェクト期間中は、イブラヒムさんが主な窓口となります。",
  },
  {
    id: "ph-np-08",
    category: "noun-phrase",
    phrase: "terms and conditions",
    meaning: "契約条件、利用規約",
    example: "Please read the terms and conditions before signing.",
    exampleTranslation: "署名の前に契約条件をお読みください。",
    note: "常に複数形。略して T&C と書かれることもある。",
  },
  {
    id: "ph-np-09",
    category: "noun-phrase",
    phrase: "letter of recommendation",
    meaning: "推薦状",
    example: "Applicants should include two letters of recommendation.",
    exampleTranslation: "応募者は推薦状を2通添えること。",
    note: "複数形にするときは letters of recommendation。letter に s を付ける。",
  },
  {
    id: "ph-np-10",
    category: "noun-phrase",
    phrase: "proof of purchase",
    meaning: "購入証明",
    example: "Refunds require proof of purchase.",
    exampleTranslation: "返金には購入証明が必要である。",
    note: "proof of identity（身分証明）、proof of address も同じ形。",
  },
  {
    id: "ph-np-11",
    category: "noun-phrase",
    phrase: "track record",
    meaning: "実績",
    example: "The contractor has a strong track record in public projects.",
    exampleTranslation: "その請負業者は公共事業で確かな実績がある。",
  },
  {
    id: "ph-np-12",
    category: "noun-phrase",
    phrase: "lead time",
    meaning: "発注から納品までの期間",
    example: "Lead times for custom parts are currently six weeks.",
    exampleTranslation: "特注部品の納期は現在6週間である。",
  },
  {
    id: "ph-np-13",
    category: "noun-phrase",
    phrase: "turnaround time",
    meaning: "処理にかかる時間",
    example: "The lab has reduced its turnaround time to 48 hours.",
    exampleTranslation: "その検査所は処理時間を48時間に短縮した。",
  },
  {
    id: "ph-np-14",
    category: "noun-phrase",
    phrase: "cash flow",
    meaning: "資金繰り、現金収支",
    example: "Late payments put pressure on the firm's cash flow.",
    exampleTranslation: "支払いの遅れが会社の資金繰りを圧迫している。",
  },
  {
    id: "ph-np-15",
    category: "noun-phrase",
    phrase: "overhead costs",
    meaning: "間接費、経常経費",
    example: "Moving to a smaller office cut overhead costs sharply.",
    exampleTranslation: "より小さな事務所への移転で、間接費が大きく減った。",
    note: "overhead だけでも同じ意味で使われる。",
  },
  {
    id: "ph-np-16",
    category: "noun-phrase",
    phrase: "agenda item",
    meaning: "議題",
    example: "The budget was the last agenda item of the meeting.",
    exampleTranslation: "予算がその会議の最後の議題だった。",
    note: "agenda は「議事日程」。個々の項目は agenda item。",
  },
  {
    id: "ph-np-17",
    category: "noun-phrase",
    phrase: "minutes of the meeting",
    meaning: "議事録",
    example: "The minutes of the meeting will be circulated on Friday.",
    exampleTranslation: "議事録は金曜日に回覧される。",
    note: "この minutes は「分」ではなく「議事録」。常に複数形。",
  },
  {
    id: "ph-np-18",
    category: "noun-phrase",
    phrase: "business hours",
    meaning: "営業時間",
    example: "Deliveries are accepted during business hours only.",
    exampleTranslation: "配送の受け取りは営業時間内のみとする。",
    note: "opening hours、office hours もほぼ同じ意味。",
  },
  {
    id: "ph-np-19",
    category: "noun-phrase",
    phrase: "shipping address",
    meaning: "配送先住所",
    example: "Please confirm the shipping address before checkout.",
    exampleTranslation: "ご購入手続きの前に配送先住所をご確認ください。",
    note: "請求先は billing address。通販の文脈で両方出る。",
  },
  {
    id: "ph-np-20",
    category: "noun-phrase",
    phrase: "range of products",
    meaning: "取扱商品の幅",
    example: "The store carries a wide range of office supplies.",
    exampleTranslation: "その店は幅広い事務用品を取り扱っている。",
    note: "a wide range of、a variety of は広告文の定番。",
  },
  {
    id: "ph-np-21",
    category: "noun-phrase",
    phrase: "customer satisfaction",
    meaning: "顧客満足度",
    example: "Customer satisfaction rose after the returns policy changed.",
    exampleTranslation: "返品規定の変更後、顧客満足度が上がった。",
  },
  {
    id: "ph-np-22",
    category: "noun-phrase",
    phrase: "safety regulations",
    meaning: "安全規則",
    example: "All staff must review the safety regulations annually.",
    exampleTranslation: "全職員は年に一度、安全規則を確認しなければならない。",
  },
  {
    id: "ph-np-23",
    category: "noun-phrase",
    phrase: "quarterly earnings",
    meaning: "四半期決算、四半期利益",
    example: "The firm will announce its quarterly earnings on 12 May.",
    exampleTranslation: "同社は5月12日に四半期決算を発表する。",
    note: "earnings は「収益」の意味では常に複数形。",
  },
  {
    id: "ph-np-24",
    category: "noun-phrase",
    phrase: "complimentary breakfast",
    meaning: "無料の朝食",
    example: "All rooms include a complimentary breakfast.",
    exampleTranslation: "全室に無料の朝食が付いている。",
    note: "complimentary は「無料の」。complementary（補完的な）と混同しやすい。",
  },
  {
    id: "ph-np-25",
    category: "noun-phrase",
    phrase: "itinerary",
    meaning: "旅程表",
    example: "Your itinerary has been e-mailed to you.",
    exampleTranslation: "旅程表をメールでお送りしました。",
    note: "出張や旅行の文脈で頻出。schedule より「行程」に近い。",
  },
]
